### PR TITLE
bugfix/renderer-crash

### LINKED ISSUE #439: Desktop app crashes on refresh
Steps to reproduce
* Open BFF desktop app (I'm on 8.1.1)
* On a Mac, hit `Cmd+R` (`Ctrl+R` on Windows, I believe)
* Application crashes (blank white screen)

So far I have been able to reproduce this with 100% consistency.

### PR DESCRIPTION
**Pull request by BrianWhitneyAI**
### Description 

The purpose of this PR is to resolve #439 and fix the broken reload. Currently if you reload the app on desktop it'll crash but another reload will fix it. This PR just adds some retry logic on the renderer. I could not identify the exact problem but it seems to be an access issue with DuckDB.

### CODE REVIEW

File: packages/desktop/src/main/index.ts [hunk 1]
```diff
@@ -49,7 +53,26 @@ const createMainWindow = () => {
...
+    mainWindow.webContents.on("crashed", (event, killed) => {
+        console.error("Renderer process crashed. Killed:", killed);
+        if (reloadAttempts < MAX_RELOAD_ATTEMPTS) {
+            reloadAttempts++;
+            console.log(`Reloading renderer... attempt ${reloadAttempts}/${MAX_RELOAD_ATTEMPTS}`);
+            setTimeout(() => {
+                if (mainWindow) {
+                    mainWindow.reload();
+                }
+            }, 1000);
```
Comment (BrianWhitneyAI) [inline packages/desktop/src/main/index.ts:66]: maybe we want less than a second here?

File: packages/desktop/src/main/index.ts [hunk 2]
```diff
@@ -49,7 +53,26 @@ const createMainWindow = () => {
...
+        } else {
+            console.error("Maximum reload attempts reached. Quitting application.");
+            app.quit();
+        }
+    });
+
     mainWindow.once("ready-to-show", () => {
+        // Reset reload counter once the renderer is successfully loaded.
+        reloadAttempts = 0;
```
Comment (aswallace) [inline packages/desktop/src/main/index.ts:75]: This does not appear to be resetting correctly. I tried just resetting the app three times in succession (each time waiting until it loaded successfully) and the count keeps adding instead of going back to zero

File: packages/desktop/src/main/index.ts [hunk 3]
```diff
@@ -26,6 +26,10 @@ app.setAppUserModelId("org.aics.alleninstitute.fileexplorer");
 // Prevent window from being garbage collected
 let mainWindow: BrowserWindow | undefined;
 
+// Maximum number of renderer reload attempts
+const MAX_RELOAD_ATTEMPTS = 3;
```
Comment (aswallace) [inline packages/desktop/src/main/index.ts:30]: Why specifically 3? If we know that for standard (non broken) refreshes it only takes 1 re-reload to work, for any other condition up to 3 probably means something is really broken and we just want it to error?

**Review by aswallace — CHANGES_REQUESTED** [review]

File: packages/desktop/src/main/index.ts (hunk 3 above)
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:30]: no real reason, 3 is just a standard I've done before for retries

File: packages/desktop/src/main/index.ts [hunk 4]
```diff
@@ -49,7 +53,26 @@ const createMainWindow = () => {
...
+            reloadAttempts++;
+            console.log(`Reloading renderer... attempt ${reloadAttempts}/${MAX_RELOAD_ATTEMPTS}`);
+            setTimeout(() => {
+                if (mainWindow) {
+                    mainWindow.reload();
+                }
+            }, 1000);
+        } else {
+            console.error("Maximum reload attempts reached. Quitting application.");
+            app.quit();
```
[the remark this answers is not in the document]
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:69]: ah yes agreed

File: packages/desktop/src/main/index.ts (hunk 2 above)
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:75]: hmm ok I will look into this

File: packages/desktop/src/main/index.ts (hunk 3 above)
Comment (SeanLeRoy) [reply packages/desktop/src/main/index.ts:30]: I agree lets just fail out after one. Are you seeing it ever continue to fail after one?

File: packages/desktop/src/main/index.ts [hunk 5]
```diff
@@ -49,7 +53,26 @@ const createMainWindow = () => {
         width: 1200,
     });
 
+    // Listen for renderer crashes and attempt a reload.
+    mainWindow.webContents.on("crashed", (event, killed) => {
```
Comment (SeanLeRoy) [inline packages/desktop/src/main/index.ts:57]: kinda crazy `crashed` is an event

File: packages/desktop/src/main/index.ts (hunk 1 above)
Comment (SeanLeRoy) [reply packages/desktop/src/main/index.ts:66]: Hmm why wait at all?

File: packages/desktop/src/main/index.ts (hunk 3 above)
Comment (SeanLeRoy) [reply packages/desktop/src/main/index.ts:30]: btw if/once you convert it to 1 retry i'd make this a boolean flag rather than a count for readability.

File: packages/desktop/src/main/index.ts (hunk 1 above)
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:66]: The idea was to account for async tasks that might not have finished/ happened in the wrong order.

File: packages/desktop/src/main/index.ts (hunk 5 above)
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:57]: yeah I'm thanking chat gpt on finding that one. Couldn't set up my own event correctly for this case.

File: packages/desktop/src/main/index.ts (hunk 3 above)
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:30]: resolved in [45ea20a](https://github.com/AllenInstitute/biofile-finder/pull/447/commits/45ea20a5e2e2f88bd759b9fa4f2922928e7ee2a8)

File: packages/desktop/src/main/index.ts (hunk 2 above)
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:75]: resolved in [45ea20a](https://github.com/AllenInstitute/biofile-finder/pull/447/commits/45ea20a5e2e2f88bd759b9fa4f2922928e7ee2a8) just use the 1did-finish-load` instead

File: packages/desktop/src/main/index.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (BrianWhitneyAI) [reply packages/desktop/src/main/index.ts:69]: resolved in [45ea20a](https://github.com/AllenInstitute/biofile-finder/pull/447/commits/45ea20a5e2e2f88bd759b9fa4f2922928e7ee2a8)

File: packages/desktop/src/main/index.ts (hunk 1 above)
Comment (SeanLeRoy) [reply packages/desktop/src/main/index.ts]: What tasks? If we have crashed can they still be running?

**Review by SeanLeRoy — APPROVED** [review]

**Review by aswallace — APPROVED** [review]
