### PR TITLE
Bugfix/Prevent attempting to load local zarr files

### LINKED ISSUE #523: App crashes for some local paths
## Description

Certain non-S3 (local aics only?) file paths cause the entire window to crash

## Expected Behavior

Should open the file details panel

## Reproduction

Go [here](https://bff.allencell.org/app?c=Experimental+Condition%3A0.25%2CGene%3A0.25%2CAntibodies+used%3A0.25%2CContent+Of+Channel+0%3A0.25%2CContent+Of+Channel+1%3A0.25%2CContent+Of+Channel+2%3A0.25%2CContent+Of+Channel+3%3A0.25&group=Antibodies+used&group=Experimental+Condition&group=Immunostaining+Set&group=Time+Of+Fixation+Post+EMT+Induction+%28in+hours%29&filter=%7B%22name%22%3A%22File+Path%22%2C%22value%22%3A%22%22%2C%22type%22%3A%22include%22%7D&filter=%7B%22name%22%3A%22Fixation+Status%22%2C%22value%22%3A%22Fixed+Cells%22%2C%22type%22%3A%22default%22%7D&openFolder=%5B%22Control+%28No+antibodies%29%22%5D&openFolder=%5B%22Control+%28No+antibodies%29%22%2C%222D+PLF+colony+EMT%22%5D&openFolder=%5B%22Control+%28No+antibodies%29%22%2C%222D+PLF+colony+EMT%22%2C%22Second+Set+Of+Immunostaining%22%5D&openFolder=%5B%22Control+%28No+antibodies%29%22%2C%222D+PLF+colony+EMT%22%2C%22Second+Set+Of+Immunostaining%22%2C%2236%22%5D&source=%7B%22name%22%3A%22pub+%285%2F6%2F2025+4%3A34%3A11+PM%29%22%2C%22type%22%3A%22csv%22%2C%22uri%22%3A%22https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vSoaR-ZYCopzyfVz_ci9D7ahNu6fSR_xqTzUH9ZvKeXwMf-NbOSmOwaAS6UUn67UX31-Vw5f0qlegnd%2Fpub%3Foutput%3Dcsv%22%7D&sort=%7B%22annotationName%22%3A%22488+Laser+Power%22%2C%22order%22%3A%22DESC%22%7D&showNulls=true), click a file, see this error: 
```
TypeError: Failed to construct 'URL': Invalid URL
    at u.value (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1686229)
    at https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:2544188
    at Ll (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1327812)
    at t.unstable_runWithPriority (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1363154)
    at Yi (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1268675)
    at kl (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1327280)
    at gl (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1318868)
    at https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1268898
    at t.unstable_runWithPriority (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1363154)
    at Yi (https://bff.allencell.org/app.13cfa08db8294beb39ba.js:2:1268675)
```

## Environment
_Which version of BioFile Finder has the bug and with what environment?_
- [x] Web
   - Browser: [e.g., Chrome, Safari]
- [ ] Desktop
   - OS: [e.g. Windows, Linux, Mac with Apple chip, Mac with Intel chip]
   - Version: [e.g. 8.1.1]

### PR DESCRIPTION
**Pull request by aswallace**
## Context
closes #523 
When users attempted to select locally-stored zarr files from the file list, the entire app would crash. This was because we were trying to read the path as an S3 url in order to calculate the zarr size.
Reproduce by going [here](https://bff.allencell.org/app?c=Experimental+Condition%3A0.25%2CGene%3A0.25%2CAntibodies+used%3A0.25%2CContent+Of+Channel+0%3A0.25%2CContent+Of+Channel+1%3A0.25%2CContent+Of+Channel+2%3A0.25%2CContent+Of+Channel+3%3A0.25&group=Antibodies+used&group=Experimental+Condition&group=Immunostaining+Set&group=Time+Of+Fixation+Post+EMT+Induction+%28in+hours%29&filter=%7B%22name%22%3A%22Fixation+Status%22%2C%22value%22%3A%22Fixed+Cells%22%2C%22type%22%3A%22default%22%7D&openFolder=%5B%22Control+%28No+antibodies%29%22%5D&openFolder=%5B%22Control+%28No+antibodies%29%22%2C%222D+PLF+colony+EMT%22%5D&openFolder=%5B%22Control+%28No+antibodies%29%22%2C%222D+PLF+colony+EMT%22%2C%22Second+Set+Of+Immunostaining%22%5D&openFolder=%5B%22Control+%28No+antibodies%29%22%2C%222D+PLF+colony+EMT%22%2C%22Second+Set+Of+Immunostaining%22%2C%2236%22%5D&source=%7B%22name%22%3A%22pub+%285%2F6%2F2025+4%3A34%3A11+PM%29%22%2C%22type%22%3A%22csv%22%2C%22uri%22%3A%22https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vSoaR-ZYCopzyfVz_ci9D7ahNu6fSR_xqTzUH9ZvKeXwMf-NbOSmOwaAS6UUn67UX31-Vw5f0qlegnd%2Fpub%3Foutput%3Dcsv%22%7D&sort=%7B%22annotationName%22%3A%22488+Laser+Power%22%2C%22order%22%3A%22DESC%22%7D&showNulls=true) and clicking on a file.

## Changes
We don't currently have the ability to read locally-stored zarrs into BFF, so this just disables the functionalities that require that (calculating size and generating thumbnails). 

## Testing
Manually tested on the link provided

### CODE REVIEW

File: packages/core/components/FileDetails/index.tsx [hunk 1]
```diff
@@ -99,7 +99,8 @@ export default function FileDetails(props: Props) {
             if (isOnWeb && isZarr) {
                 if (fileDetails.size && fileDetails.size > 0) {
                     setCalculatedSize(fileDetails.size);
-                } else {
+                } else if (fileDownloadService.isS3Url(fileDetails.path)) {
+                    // Currently unable to calculate file size for local, non-s3 zarr files
```
Comment (BrianWhitneyAI) [inline packages/core/components/FileDetails/index.tsx:103]: I think we could support non-s3 files, we would just need a way to list their subfiles. Local we cannot do from web since we need permission for every subfile (>10,000 in some cases)

File: packages/core/entity/FileDetail/index.ts [hunk 2]
```diff
@@ -146,6 +146,10 @@ export default class FileDetail {
         return path as string;
     }
 
+    public get isLikelyLocalFile(): boolean {
```
Comment (BrianWhitneyAI) [inline packages/core/entity/FileDetail/index.ts:149]: This feels a little weird to me. Could we have a different condition? Are there other cases where a file doesn't start with http or s3 that the file would be cloud? will it always have that at the beginning of the path?

Comment (BrianWhitneyAI) [reply packages/core/entity/FileDetail/index.ts:149]: Ah I see this is from before.

**Review by BrianWhitneyAI — APPROVED** [review]

File: packages/core/components/FileDetails/index.tsx (hunk 1 above)
Comment (SeanLeRoy) [reply packages/core/components/FileDetails/index.tsx:103]: >Local we cannot do from web since we need permission for every subfile (>10,000 in some cases)

Can you re-phrase this? I don't think I understand, are you saying locally (i.e. on desktop?) we can't get files from S3 files?

File: packages/core/components/FileDetails/index.tsx [hunk 3]
```diff
@@ -99,7 +99,8 @@ export default function FileDetails(props: Props) {
             if (isOnWeb && isZarr) {
```
Comment (SeanLeRoy) [inline packages/core/components/FileDetails/index.tsx:99]: I know this isn't part of this work - but why can't we create a thumbnail for desktop users? @BrianWhitneyAI is this what your other comment is about?

File: packages/core/entity/FileDetail/index.ts (hunk 2 above)
Comment (SeanLeRoy) [reply packages/core/entity/FileDetail/index.ts:149]: We should try to add whatever Google/Microsoft's cloud platform protocol is (assuming they have one) at some point perhaps. Although I've never heard of a lab using Microsoft's so maybe just Google...

**Review by SeanLeRoy — APPROVED** [review]

File: packages/core/entity/FileDetail/index.ts (hunk 2 above)
Comment (aswallace) [reply packages/core/entity/FileDetail/index.ts:149]: Yeah, this was just me moving pre existing code. Happy to change to something more comprehensive

File: packages/core/components/FileDetails/index.tsx (hunk 3 above)
Comment (BrianWhitneyAI) [reply packages/core/components/FileDetails/index.tsx:99]: It's honestly been a while since I've looked into this, but I think that reading a local file from the web requires lots of subfile access. Id have to double check the dependency and test if for thumbnails to verify but knowing how zarrs are organized I would guess we have the same problem as the size request.

File: packages/core/entity/FileDetail/index.ts (hunk 2 above)
Comment (aswallace) [reply packages/core/entity/FileDetail/index.ts:149]: I'll leave this as is for now. I believe the Google url protocol is `gs://`, but will hold off until we have use cases

File: packages/core/components/FileDetails/index.tsx (hunk 1 above)
Comment (BrianWhitneyAI) [reply packages/core/components/FileDetails/index.tsx:103]: I was trying to say that I think we could support other cloud locations from web (ex. Google/Microsoft) I just haven't seen any examples.

The second sentence is saying we cannot do local access for web because of the multifile structure and how web browsers allow access to files.

**Comment by aswallace** [comment]
I'd like to at least get the temporary fix deployed, so I'm going to merge this as is (since it doesn't actually change current functionality, just prevents users from hitting those cases) and then will open a couple tickets for exploring/addressing some zarr accessibility things.

**Comment by aswallace** [comment]
I'd like to at least get the temporary fix deployed, so I'm going to merge this as is (since it doesn't actually change current functionality, just prevents users from hitting those cases) and then will open a couple tickets for exploring/addressing some zarr accessibility things.
