### PR TITLE
bugfix/ZEN-wrong-path

### LINKED ISSUE #401: BFF fails to open file in Zen
Sara was working with BFF, and tried to send a file to Zen.  Zen started up, but did not view the file.
She was able to open the file from Zen by manually selecting it based on the displayed BFF file path on the vast.
Slack conversation here: 
https://allencellscience.slack.com/archives/C021CEY96LD/p1738092593969209

### PR DESCRIPTION
**Pull request by BrianWhitneyAI**
### Description 
The purpose of this PR is to resolve #401 and allow scientists to open local files ( VAST ) in ZEN. When we switched to cloud path being our primary path we then pass this path to external apps that try to "open it". This means that apps that need a local path like ZEN cannot open these paths.

### Development Decisions

In order to complete this PR we had to make a few decisions.

1) Desktop apps will default to using local path. This means that any app that users add will automatically use local path.
2) Disable desktop applications for cloud only files.

In the future if we want specific apps to use a cloud path then we need to add them manually to the repo, otherwise it'll default to opening with the local path.

### CODE REVIEW

**Comment by SeanLeRoy** [comment]
Is this a draft?

**Comment by BrianWhitneyAI** [comment]
Ok I tested this through Remote Desktop. Files that are cloud only grey out ZEN as an option and files that are in local cache open correctly in ZEN

File: packages/core/state/interaction/logics.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import { isEmpty, sumBy, throttle, uniq, uniqueId } from "lodash";
+import { isAbsolute } from "path";
```
Comment (SeanLeRoy) [inline packages/core/state/interaction/logics.ts:2]: isn't path a `node` module aka not available for web deploys?

File: packages/core/state/interaction/logics.ts [hunk 2]
```diff
@@ -489,8 +490,14 @@ const openWithLogic = createLogic({
         } else {
             filesToOpen = await fileSelection.fetchAllDetails();
         }
+
+        // Determine if exePath is local
+        const isLocalExecutable = isAbsolute(exePath);
```
Comment (SeanLeRoy) [inline packages/core/state/interaction/logics.ts:495]: I suppose it is likely we will always store the path as absolute for local executables but it does seem potentially buggy with the way certain systems mount apps - I'm pretty sure `executionEnvService` is only used for local apps anyway right? Couldn't we just assume they are always local?

File: packages/core/hooks/useOpenWithMenuItems/index.tsx [hunk 3]
```diff
@@ -222,7 +222,7 @@ export default (fileDetails?: FileDetail, filters?: FileFilter[]): IContextualMe
                 key: `open-with-${name}`,
                 text: name,
                 title: `Open files with ${name}`,
-                disabled: !filters && !fileDetails,
+                disabled: (!filters && !fileDetails) || !fileDetails?.localPath,
```
[the remark this answers is not in the document]
Comment (kmitcham) [reply packages/core/hooks/useOpenWithMenuItems/index.tsx:225]: Is the user experience better with mysterious opening failures or reduced options, which seem to be the choices?  Or do we want to undertake tracking which apps are cloud ready, and showing the appropriate items for the situation?

File: packages/core/state/interaction/logics.ts (hunk 1 above)
Comment (BrianWhitneyAI) [reply packages/core/state/interaction/logics.ts:2]: ah rats I always forget about this. (And didn't test it on web since I was using a remote workstation)

**Review by kmitcham — APPROVED** [review]

**Review by SeanLeRoy — APPROVED** [review]
